env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-console: 0
  comma-dangle: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - always
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]